# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
name: Mirror Sync To Gitea
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v2
    - name: sync github  ->  gitee
      uses: Yikun/hub-mirror-action@master
      with:
        src: github/innetemail
        dst: gitee/innetemail
        clone_style: "ssh"
        debug: true
        force_update: true
        dst_key: ${{ secrets.TESTPRIVATEKEY }}
        dst_token:  ${{ secrets.GITEE_TOKEN }}
